# Generated by Django 5.2.9 on 2025-12-16 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_sessions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionlog',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='patient_sessions.session'),
        ),
    ]
