# Generated by Django 5.2.9 on 2025-12-14 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_alter_device_clinic'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='api_key',
            field=models.CharField(default='temp_api_key', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
