# Generated by Django 5.2.9 on 2025-12-20 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportgeneration',
            name='file_path',
            field=models.FileField(blank=True, null=True, upload_to='reports/'),
        ),
    ]
