# Generated by Django 5.2.9 on 2025-12-27 10:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('patient_code', models.CharField(max_length=20, unique=True)),
                ('personal_data', models.JSONField(help_text='\n        patient personal information:\n        {\n          "first_name": "",\n          "last_name": "",\n          "gender": "",\n          "birth_date": "",\n          "national_id": "",\n          "phone": "",\n          "email": "",\n          "address": ""\n        }\n        ')),
                ('consent', models.JSONField(help_text='Patient consent data: ')),
                ('indication', models.JSONField(help_text='Medical indication data: ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='accounts.clinic')),
            ],
        ),
        migrations.CreateModel(
            name='PatientToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, unique=True)),
                ('clinic_id', models.CharField(max_length=100)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='patients.patient')),
            ],
        ),
    ]
