# Generated by Django 5.2.9 on 2025-12-13 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=100, unique=True)),
                ('patient_firstname', models.CharField(max_length=50)),
                ('patient_lastname', models.CharField(max_length=50)),
                ('patient_address', models.CharField(max_length=100)),
                ('patient_email', models.CharField(max_length=50)),
                ('patient_phone', models.CharField(max_length=50)),
                ('patient_birthdate', models.DateField(null=True)),
                ('patient_gender', models.CharField(max_length=10)),
                ('extra_info', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='accounts.clinic')),
            ],
        ),
    ]
