# Generated by Django 5.2.9 on 2025-12-14 06:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_remove_patient_extra_info_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='extra_information',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='national_id',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='patient_address',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='patient_birthdate',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='patient_email',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='patient_firstname',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='patient_gender',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='patient_lastname',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='patient',
            name='consent',
            field=models.JSONField(default={}, help_text='Patient consent data: '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='indication',
            field=models.JSONField(default={}, help_text='Medical indication data: '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='personal_data',
            field=models.JSONField(default={}, help_text='\n        patient personal information:\n        {\n          "first_name": "",\n          "last_name": "",\n          "gender": "",\n          "birth_date": "",\n          "national_id": "",\n          "phone": "",\n          "email": "",\n          "address": ""\n        }\n        '),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
